-- Run this script while connected to database: bca-g6

BEGIN;

CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS operator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    created_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_operator_role CHECK (role IN ('OPERATOR', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS complaint_status (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    comment TEXT
);

CREATE TABLE IF NOT EXISTS refusal_reason (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS complaint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status_id SMALLINT NOT NULL,
    created_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_dttm TIMESTAMPTZ,
    subject VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    draft_email_subject VARCHAR(255),
    draft_email_body TEXT,
    operator_id BIGINT,
    refusal_reason_id SMALLINT,
    CONSTRAINT fk_complaint_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_complaint_status FOREIGN KEY (status_id) REFERENCES complaint_status (id),
    CONSTRAINT fk_complaint_operator FOREIGN KEY (operator_id) REFERENCES operator (id),
    CONSTRAINT fk_complaint_refusal_reason FOREIGN KEY (refusal_reason_id) REFERENCES refusal_reason (id)
);

CREATE TABLE IF NOT EXISTS bank_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    created_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    account_number VARCHAR(34) NOT NULL UNIQUE,
    currency CHAR(3) NOT NULL,
    balance NUMERIC(18, 2) NOT NULL DEFAULT 0,
    account_type VARCHAR(20) NOT NULL,
    CONSTRAINT fk_bank_account_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT chk_bank_account_type CHECK (account_type IN ('CHECKING', 'SAVINGS', 'CREDIT')),
    CONSTRAINT chk_bank_account_balance CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS complaint_status_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    status_id SMALLINT NOT NULL,
    updated_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_status_log_complaint FOREIGN KEY (complaint_id) REFERENCES complaint (id),
    CONSTRAINT fk_status_log_status FOREIGN KEY (status_id) REFERENCES complaint_status (id)
);

CREATE TABLE IF NOT EXISTS complaint_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    mime_type VARCHAR(255),
    file_size BIGINT,
    uploaded_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_attachment_complaint FOREIGN KEY (complaint_id) REFERENCES complaint (id),
    CONSTRAINT chk_attachment_file_size CHECK (file_size IS NULL OR file_size >= 0)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    performed_by VARCHAR(100) NOT NULL,
    performed_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    details JSONB,
    CONSTRAINT chk_audit_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE'))
);

CREATE INDEX IF NOT EXISTS idx_complaint_status_id ON complaint (status_id);
CREATE INDEX IF NOT EXISTS idx_complaint_customer_id ON complaint (customer_id);
CREATE INDEX IF NOT EXISTS idx_complaint_created_dttm ON complaint (created_dttm);
CREATE INDEX IF NOT EXISTS idx_complaint_status_log_complaint_id ON complaint_status_log (complaint_id);

CREATE OR REPLACE FUNCTION set_complaint_updated_dttm()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    NEW.updated_dttm = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_complaint_updated_dttm ON complaint;
CREATE TRIGGER trg_complaint_updated_dttm
BEFORE UPDATE ON complaint
FOR EACH ROW
EXECUTE FUNCTION set_complaint_updated_dttm();

COMMIT;
