-- Agent integration: add AI processing columns and agent_log table
-- Run after 02_seed.sql

BEGIN;

-- New columns on complaint for agent processing results
ALTER TABLE complaint ADD COLUMN IF NOT EXISTS extracted_data TEXT;
ALTER TABLE complaint ADD COLUMN IF NOT EXISTS category VARCHAR(512);
ALTER TABLE complaint ADD COLUMN IF NOT EXISTS recommendation VARCHAR(50);
ALTER TABLE complaint ADD COLUMN IF NOT EXISTS recommendation_reasoning TEXT;

-- Agent processing log table
CREATE TABLE IF NOT EXISTS agent_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    agent_name VARCHAR(100) NOT NULL,
    action_type VARCHAR(100) NOT NULL,
    input_context TEXT,
    reasoning_process TEXT,
    output_context TEXT,
    created_dttm TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_agent_log_complaint FOREIGN KEY (complaint_id) REFERENCES complaint (id)
);

CREATE INDEX IF NOT EXISTS idx_agent_log_complaint_id ON agent_log (complaint_id);

COMMIT;
